### ISSUE TITLE
Shiny application review

### ISSUE THREAD

**Issue by abishek-murali** [johannesharmse/Shiny_Google_Browser_History#1]
> The idea for this application is really cool. I loved the idea of being able to visualize your search history based on location. I think it has great potential!
>
> The one thing that I noticed was just the flow of uploading data, filtering it and adding phrases was a tad confusing. I tried navigating horizontally but did not realize that the navigation of filters was vertical. This could be made easy by using a tab and box option available in `Shiny dashboard`
>
> What could be improved? In terms of the idea of visualization, absolutely nothing. The only aspect I would consider is just the general layout of the application filters and navigation. The one thing I noticed was I was able to add an empty phrase in the `Add phrase` filter menu. This could lead to confusing results if the user clicks add phrase without entering a phrase.
>
> Overall Impression: This is a brilliant idea and with subtle changes this application has great potential. Great job!

**Comment by johannesharmse** [comment]
Thanks for the positive feedback!

The layout has now been updated to a `Shiny dashboard` layout as suggested.

The `Add phrase` bug has also been fixed.
