### ISSUE TITLE
Peer Review of Browser History Assistant

### ISSUE THREAD

**Issue by avinashkz** [johannesharmse/Shiny_Google_Browser_History#2]
The Browser History Assistant is a brilliant idea and very useful application for filtering your browser history and finding something that would have been very hard to find by just searching in the browser. There are also a wide variety of filtering options that can be useful for users who are trying to find something particular. Also, the map has been integrated such a way that it is very useful for the user can filter the history based on location in which they have viewed websites. I was also equally impressed by the way in which all the complex features were integrated together to enhance the usability. 

The only issue I faced when using the application due to resource limitations of hosting the app in shinyapp.io was the slight delay in updating the table when the size of the data uploaded is very high. 

Other than the minor delay when using the application, it is very well designed and developed. Great Job!!

**Comment by johannesharmse** [comment]
Thanks for the positive feedback!

For now, the app will live on shinyapps.io, but if there is a demand for it, it might be moved to a server with sufficient resources. 

In addition, the sample data has been reduced in size and stored as a data frame object to increase the upload and processing speed of the app when playing around with the sample data.
